version: 2.1
executors:
  my-custom-executor:
    docker:
      - image: cimg/android:2021.10.2
        auth:
          # ensure you have first added these secrets
          # visit app.circleci.com/settings/project/github/jurgenneeme/autocomplete/environment-variables
          username: $DOCKER_HUB_USER
          password: $DOCKER_HUB_PASSWORD
jobs:
  my-job-name:

    executor: my-custom-executor
    steps:
      - checkout
      - run: |
          jobs:
            build:
              docker:
                - image: cimg/android:2021.10.2
              steps:
                - checkout
                - run: ./gradlew androidDependencies
                - run: ./gradlew lint test

workflows:
  my-custom-workflow:
    jobs:
      - my-job-name